version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/employee_management
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend/101396295_comp3123_assignment2_reactjs
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: